#include <iostream>
#include <cmath>
#include <cstdlib>
#include <chrono>
/*

    Input: Array/String of letters.
    Output: Calculate formulaic sum.
    To-do: Make letterDist faster via closed form solution.
           Add single sum solution using partitioning.
*/

using namespace std;
using namespace chrono;

int letterDist(string sCase){
    int sum = 0;
    int n = sCase.size();
    for (int i = 0 ; i < n ; i++){
        for (int j = i ; j < n; j++){
            sum += (pow(j-i,2)) * ((sCase[i] != sCase[j]) ? 1 : 0);
        }
    }
    
    return sum % 1000000007;

}

int main(){
    cout << letterDist("ICPC") << endl;
    cout << letterDist("SOCAL") << endl;
    cout << letterDist("ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ") << endl;
    cout << letterDist("JMNFUITHXZRUIDPMCDALAVVGPIRDMZJWWZQRIOWOFABQZARZZSAGPGDTEKUGKHEHQCHQMEZIZIEVLZUOELSNLQNXRUELFIJPFRAQNYJSTDHWFRMTWOYCEMUWITIMKXDNCOIUBLVPVDEUZUKURCFLDMPQXWTWPZNWDUWZAILBJBZMOLOSSMDDMOVCYHJAGONILSQAQBISQDNYUQPNIJFHDXPFUSBCXUEUKYGBTKSJAPJUDPAPVOWLWKWXNFYPQVYPKIZANSGHKEVTTLYZDQBMPTNXUPHIPIAHEIVKKZWZMSDUJSGCFQHGJYRKSVHDUTAHXHLUERHRTTMYHINGWNHSYOXVTHJXAMDMBEHKYZGHBOWDYQKHKQARZNFAZBMLLMCQTQNDIZPDYRENRLPOODILGVEDELDZFKYHHAZGRZDZFDXCIKNOWMGPSQXBIYLJCCCYDNFISWCPFSIOPJGAQBBKZDDZEUIOEIJEFMYHQWNMEQKRQCSTSDODZHJUYRHTDLAMFCBLIAABZUONRVKDKZESHOVYPYBXRVHLZQLTKMAVCIDUFUJKKLUTTSKMBWFECQDXVWCERKIEBHRQRAFRQPPZEBKVPJQGBKHUPEPRYDJAGBHMNHQLVDGZSGWZHVZTKMUJWNDOJJUEDMPDEVDNJYSTESYCJAXNSPDXYFJOZIVDSLFAYYWLHILAOKZPGOVQWSNGCIWPOVDCTSMPXRABSRCBIVYPAHEKQYVVJJMMCHSYMJDSZGGHCSYGAEQEANWTOMTDLIWCPVTVIHQEUVLFPCCICWKXSWAJRBWWIVWXSGARJCBEGVKFQLPQTCQDJMZYAOYHTJRYHXSBZGTFYZMSEXQOPZHKPNACJIVDFLZPHNCWGMOLQFWLBGAFLFVFSGGHZDOYCVHHPNMIUMFCFTCVMEDPXSWTOUBMWDEFNVCTHEEUPVRCMSRODXCFCRDUBXYCQFMUURATYERBPTTFTOQFGTCCUYRHSNBEVMFOPEQKHPBN");

    return 0;
}
